name: Release Builds

on:
  workflow_dispatch:
  push:
    paths:
      - '**/builds.yml'
      - '**/download-builds.sh'
  schedule:
    - cron: '0 0 1 * *'

jobs:
  release-builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: echo "date=$(date +'%Y%m%d')" >> "$GITHUB_OUTPUT"
        id: date
      - run: sudo sh ./scripts/download-builds.sh
        id: builds
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.builds.outputs.linux-path }}
            ${{ steps.builds.outputs.win32-path }}
            ${{ steps.builds.outputs.darwin-path }}
