name: Tests

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 2

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Run FedericoCarboni/setup-ffmpeg
        uses: ./
      - name: Run FedericoCarboni/setup-ffmpeg
        id: setup-ffmpeg
        uses: ./
      - run: ffmpeg -version
      - run: ffprobe -version
      - name: Run FedericoCarboni/setup-ffmpeg
        uses: ./
        with:
          version: release
      - name: Run FedericoCarboni/setup-ffmpeg
        id: setup-ffmpeg1
        uses: ./
        with:
          version: release
      - run: ffmpeg -version
      - run: ffprobe -version
